language: java

# explicit distribution specification
dist: xenial

jdk: openjdk8

git:
  depth: false

services:
   - docker
   - xvfb

addons:
  sonarcloud:
    organization: "alessandroferi-github"

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2
      - $HOME/.sonar/cache

script:
   - mvn -f simple-sonarqube-example/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent clean verify sonar:sonar 